### ISSUE TITLE
Scopes are not being created in activerecord 4.1.9

### ISSUE THREAD

**Issue by rosskevin** [state-machines/state_machines-activerecord#11]
When debugging [scope creation](https://github.com/state-machines/state_machines/blob/master/lib/state_machines/machine.rb#L2115), it appears that the #define_helper method is never called.

Here's the snippet from the link above:

```ruby
    def define_scopes(custom_plural = nil)
      plural = custom_plural || pluralize(name)

      [:with, :without].each do |kind|
        [name, plural].map { |s| s.to_s }.uniq.each do |suffix|
          method = "#{kind}_#{suffix}"

          if scope = send("create_#{kind}_scope", method)
            # Converts state names to their corresponding values so that they
            # can be looked up properly
            define_helper(:class, method) do |machine, klass, *states|
              run_scope(scope, machine, klass, states)
            end
          end
        end
      end
    end
```

The `send` in debug mode equates to:

```ruby
scope = send("create_without_scope", 'without_states')
```

This hits the [no-op #create_without_scope](https://github.com/state-machines/state_machines/blob/master/lib/state_machines/machine.rb#L2155).  

How is the `StateMachines::Integrations::ActiveRecord#create_without_scope` intended to be wired in to override the same method in `machines.rb`?

**Comment by rosskevin** [comment]
@seuros this is a show stopper for me.  I'm happy to dig in and fix it but need to be pointed in the right direction.  Perhaps a usage error, or documentation needs updated?  

I've traced it back further to [`Integrations`](https://github.com/state-machines/state_machines/blob/master/lib/state_machines/integrations.rb#L79).  `@integrations` is an empty array so I'm assuming that I've misconfigured or this module is not registering itself.  [`#register`](https://github.com/state-machines/state_machines/blob/master/lib/state_machines/integrations.rb#L27) is never called.

**Comment by seuros** [comment]
Thank you for your input.

`#register` is in fact used in the integrations, for example : https://github.com/state-machines/state_machines-activerecord/blob/master/lib/state_machines/integrations/active_record.rb#L562

**Comment by rosskevin** [comment]
@seuros  Found it! Simple problem but I think the readme needs updated:

```ruby
require 'state_machines'
require 'state_machines-activerecord'
```
I didn't require it anywhere and expected auto-detection.

**Comment by seuros** [comment]
Bundler should require them by default. 
Else you can require just 'state_machines-activerecord'

**Comment by rosskevin** [comment]
This may be due to the fact that these models are in a rails Engine.

**Comment by seuros** [comment]
If state_machines-activerecord is part of your Gemfile, it should work.

**Comment by rosskevin** [comment]
They are in the gemspec, but weren't required by default:

```
  s.add_dependency 'state_machines'
  s.add_dependency 'state_machines-activerecord
```

**Comment by seuros** [comment]
I'm facing this exact issue in one of my project (with anothe gems), maybe it a bug in rails. 

PS, you don't need to add state_machines as dependency too, state_machines-activerecord depend on state_machines-activemodel and state_machines.

**Comment by rosskevin** [comment]
Got it, thank you for the quick assistance.
