### ISSUE TITLE
Default translations not used

### ISSUE THREAD

**Issue by aripollak** [state-machines/state_machines-activerecord#14]
The docs for this gem say that default :en translations are set, but apparently they are not used in Rails 4.2.1. In a freshly generated Rails project with this gem added, inside a `rails console`:

```ruby
irb(main):003:0> I18n.t!('activerecord.errors.messages.invalid_transition')
I18n::MissingTranslationData: translation missing: en.activerecord.errors.messages.invalid_transition
```

**Comment by rosskevin** [comment]
@aripollak if you could submit a test, that would be most helpful. I'm on rails 4.2.1 and don't have a problem.  Are you still seeing it?

**Comment by aripollak** [comment]
Very strange, I'm not seeing a problem anymore, even though I don't see any changes about it. I guess I must have led myself down the wrong path to where the problem was!

**Comment by aripollak** [comment]
Oh, the problem was due to me defining an I18n exception handler in the test environment that raised exceptions on a missing translation instead of catching it like normal. It didn't work with the `default` option correctly, which hadn't been a problem until using this particular gem.
