### ISSUE TITLE
multiple machines per model ?

### ISSUE THREAD

**Issue by jshow** [state-machines/state_machines-activerecord#15]
Greetings,

I'm looking for an implementation that supports multiple fsm.

The originating project advertised multiple state machines per object - the current docs don't explicitly say this is the case.

thanks.
Jodi

**Comment by seuros** [comment]
It is the case :smile_cat: .

**Comment by jshow** [comment]
fantastic - I will see if I can figure it out, and may recommend a documentation change

cheers @seuros  (-:

**Comment by seuros** [comment]
```ruby
state_machine :state, initial: :active do 
#
end
state_machine :stock_state, initial: :empty do
#
en

**Comment by jshow** [comment]
:+1: :boom: !
