### ISSUE TITLE
Observers aren't working

### ISSUE THREAD

**Issue by JohnSmall** [state-machines/state_machines-activerecord#21]
I replaced my existing statemachine gem with this one so I could move up to Rails 4.2 and found that my observers aren't getting triggered.

Did that code get left behind? The documentation suggests that it should work with observers, but that's just been copied across from the old state_machine gem. 

Where do I need to look in the code to fix this?

**Comment by seuros** [comment]
For some reason i forgot to update https://github.com/state-machines/state_machines-activemodel-observers

**Comment by seuros** [comment]
@JohnSmall can you add that gem and try again ?
