### ISSUE TITLE
get value for state name?

### ISSUE THREAD

**Issue by arches** [state-machines/state_machines-activerecord#27]
I have a bunch of states defined with custom values.  How can I retrieve the value for a given state?  Thanks!

**Comment by rosskevin** [comment]
@arches can you give me a better description?  Also, unless this is related to the activerecord integration, this might be better asked in the parent project, https://github.com/state-machines/state_machines/issues

In the parent project readme, it shows (and I use it this way):

```ruby
vehicle.state                   # => "parked"
vehicle.state_name              # => :parked
```

**Comment by arches** [comment]
My setup:
```ruby
class Vehicle
  state_machine :state do
    state :parked, value: 0
  end
end
```

My goal is to turn `:parked` back into `0`, for example:
```ruby
Vehicle.state_value(:parked) # => 0
```

(Sorry to ask in the wrong place, I got here from https://github.com/pluginaweek/state_machine/issues/343)

**Comment by rosskevin** [comment]
I'm not sure, but I'm curious to know as well. @renchap in #13 might be interested too.  I'd definitely close this one and ask in the parent, might get more help.  Also, thanks for the note about where you came from, I asked @styxx to make an update to the link.

**Comment by arches** [comment]
ok, thanks @rosskevin!  moved to https://github.com/state-machines/state_machines/issues/22
