### ISSUE TITLE
Implicit even triggers do not work inside of callbacks

### ISSUE THREAD

**Issue by andytcox** [state-machines/state_machines-activerecord#29]
I'm on Rails 4.1.1 and the following behavior seems a bit odd and I'm wondering if its a limitation in the way transitions are done, or possibly a bug(I may also be doing something wrong here)

My Model
```ruby
class Event < ActiveRecord::Base

    before_validation :transition_status, :on => :update

    def transition_status
      self.status_event = :was_updated
    end

    state_machine :status, :initial => :new do
      event :pend do
        transition [:new, :confirmed] => :pending, :unless => :start_date_passed?
      end
      event :was_updated do
        transition [:new, :pending, :confirmed] => :pending
      end
      event :confirm do
        transition :pending => :confirmed
      end
   end
end
```

Now some sample code:
```ruby
@event = Event.first
@event.confirmed? # => true
@event.update_attribute(:start_date => @event.start_date + 1.day)
@event.reload.status # => confirmed
@event.confirmed? # => true
```
**note** Assigning using `@event.start_date` and then using `#save` has the same effect

I expected this to change the status back to `pending`, but it never seems to apply the transition when its called(or assigned) in the callback. 

My only thought here is that the `#around_save` documented [here](https://github.com/state-machines/state_machines-activerecord/blob/master/lib/state_machines/integrations/active_record.rb#L492) "prevents" the `before_transition` from being called and therefore the implicit state change never runs. This is partially supported by the evidence [here](https://github.com/state-machines/state_machines-activerecord/blob/master/lib/state_machines/integrations/active_record.rb#L287)

At the bottom of [this](https://github.com/state-machines/state_machines-activerecord/blob/master/lib/state_machines/integrations/active_record.rb#L287) section in the main state machine docs, they say
`See each integration's API documentation for more information on the implicit approach.`

Searching the entire repo here yields no results for `implicit`. I'd be glad to submit a PR with some updated info after I've cleared up my current issue.

**Comment by jiongye** [comment]
I am trying to switch the old state_machine gem to this gem because old one is not active anymore. 
Our app use Rails 4.1.7 and Ruby 2.1.2, we also experience a similar problem with the observer. We use the "after_'event'" hook to trigger some callback a observer, but that hook never triggered.   It works fine with the old state_machine gem.

**Comment by seuros** [comment]
@jiongye I think you should add : https://github.com/state-machines/state_machines-activemodel-observers

**Comment by jiongye** [comment]
@seuros Thank you for pointing that out. That fixed my issue.

**Comment by codemilan** [comment]
@andytcox @seuros Is there any way to trigger events in model callbacks, I'm working on an existing app that has much more creation/updation code on controllers/models for state_machined model. I would like to have triggering of events from one central place i.e. model callback based on some attributes value, below is the sample model code, I would like to get suggestion if I'm doing something wrong or undoable :
```ruby
class Response < ApplicationRecord
  state_machine initial: :created do

    after_transition on: :fire_answered, do: [:run_metrics]

    after_transition on: :fire_review, do: [:check_review]

    event :fire_sent do
      transition from: [:created, :sent], to: :sent
    end
    event :fire_review do
      transition from: [:sent, :answered], to: :review
    end
    event :fire_answered do
      transition from: [:sent, :review, :answered], to: :answered
    end
  end

  before_save :set_appropriate_events

  def set_appropriate_events
    # This doesn't trigger events, only sets 'state_event'
    self.state_event = 'fire_sent' if sent_time.present? && response_time.blank?
    self.state_event = 'fire_answered' if sent_time.present? && response_time.present?
    self.state_event = 'fire_review' if needs_review?

    # On doing below gives "SystemStackError: stack level too deep"
    # self.fire_sent if self.sent_time.present? && self.response_time.blank?
    # self.fire_answered if self.sent_time.present? && self.response_time.present?
    # self.fire_review if self.needs_review?
  end
end

**Comment by seuros** [comment]
I will need more details . The model is stripped from the code that code the error.
