### ISSUE TITLE
Around save bug: record saved twice

### ISSUE THREAD

**Issue by tesserakt** [state-machines/state_machines-activerecord#30]
Hi all, 

In Spree I have enabled transactions for the order state machine. Now with inventory units, whenever one is saved, the around_save block gets called and saves it again. It is quite strange, but I end up with 2 inventory_units with I only needed one. Have any of you seen anything similar?

**Comment by seuros** [comment]
Can you provide a demo app ? It will make debugging much faster.

**Comment by tesserakt** [comment]
@seuros I think this is a Spree bug actually around the way the InventoryUnitBuilder works
