### ISSUE TITLE
Doesn't seem to respect conditional validations

### ISSUE THREAD

**Issue by UnderpantsGnome** [state-machines/state_machines-activerecord#33]
I have a model with a conditional validation

    validates :nda_accepted,
      presence: true,
      unless: :draft?

but if I try to transition it fails.

    >> Rfq.last.valid?
    => true
    >> Rfq.last.delete_draft!
    StateMachines::InvalidTransition: Cannot transition state via :delete_draft from :draft (Reason(s): Nda accepted can't be blank)
    from /Users/mmoen/code/UnderpantsGnome/britehub-app/vendor/bundle/ruby/2.2.0/gems/state_machines-0.4.0/lib/state_machines/event.rb:224:in `block in add_actions'

Gems

    gem 'state_machines', '~> 0.4.0'
    gem 'state_machines-activerecord', '~> 0.3.0'
    gem 'state_machines-activemodel', '~> 0.3.0'

**Comment by seuros** [comment]
If you could provide a sample app with sqlite3 so we can debug it quickly ?

**Comment by UnderpantsGnome** [comment]
Here you go https://github.com/UnderpantsGnome/state_machine_validations

**Comment by juank-pa** [comment]
I'm going to take a look at it

**Comment by seuros** [comment]
Thank you @UnderpantsGnome @juank-pa

**Comment by juank-pa** [comment]
The exception actually makes sense in this scenario. At start, validation is not being performed on creation because the state is `draft`. But once you change the state to `deleted`, validations are performed prior to updating the db and using the local data which has `deleted` as your state. The following example solves this:
```
  validates :nda_accepted,
    presence: true,
    unless: :should_validate?

  state_machine :state, initial: :draft do
    event :delete_draft do
      transition [:draft] => :deleted
    end
    event :publish do
      transition [:draft] => :published
    end
  end

  def should_validate?
    draft? || deleted?
  end
```

**Comment by juank-pa** [comment]
After pairing with @seuros we came up with a cleaner solution:

```
state_machine :state, initial: :draft do
    event :delete_draft do
      transition [:draft] => :deleted
    end
    event :publish do
      transition [:draft] => :published
    end
    state :published do
      validates :nda_accepted, presence: true
    end
  end
```

**Comment by UnderpantsGnome** [comment]
@juank-pa @seuros oh nice! I didn't realize I could handle the validations that way. Guess I need to look at the active model docs.

Thanks for the help
