### ISSUE TITLE
Default transition action

### ISSUE THREAD

**Issue by xxswingxx** [state-machines/state_machines-activerecord#4]
Hi!
Is it intended not to set `save` as the default action in a transition or is something you are considering to add in the future?

**Comment by seuros** [comment]
@xxswingxx You can overwrite the default action with the `action` options

**Comment by xxswingxx** [comment]
You mean by modifying this hash? 

```ruby
StateMachines::Integrations::ActiveRecord.defaults
```

Weird thing is that it returns `{ :action => :save}` by default but as far as I have tested the record is not being saved.

**Comment by seuros** [comment]
```ruby
state_machine :initial => :draft, :action => :another_action do
#...
end
```

**Comment by xxswingxx** [comment]
Thanks!

**Comment by seuros** [comment]
If that resolve your issue, please close this issue. :smiley_cat:

**Comment by xxswingxx** [comment]
:+1:
