### ISSUE TITLE
Get transition information in around_transition

### ISSUE THREAD

**Issue by jeffblake** [state-machines/state_machines-activerecord#40]
I am wanting to benchmark the transition and send to a metric service.. but I can't seem to get the destination state, only the current state.

**Comment by seuros** [comment]
The transition (StateMachines:Transition) has the from and to name.

**Comment by jeffblake** [comment]
Hmm, this is what I have:

```
    around_transition do |payment, transition|
      byebug
      Librato.timing "#{payment.metric_namespace}.#{transition.to}", source: payment.metric_source do
        yield
      end
    end
```

The payment = payment (expected)
The transition = Proc 

What am I doing wrong?

**Comment by jeffblake** [comment]
Nevermind, I had to add a third argument.
