### ISSUE TITLE
0.4.0 release?

### ISSUE THREAD

**Issue by connorshea** [state-machines/state_machines-activerecord#41]
Will 0.4.0 stable be released to RubyGems any time soon? Would be nice for Rails 5 support.

**Comment by seuros** [comment]
yes, we will release it once rails 5 is released.

**Comment by connorshea** [comment]
@seuros Rails 5.0.0.rc1 released today: https://github.com/rails/rails/releases/tag/v5.0.0.rc1

There shouldn't be any breaking changes between rc1 and stable.

**Comment by pboling** [comment]
Would be great to release the new gem before Rails 5 GM is released so people can test against their Rails 5 upgrade branches more easily.

**Comment by seuros** [comment]
@pboling @connorshea 

```ruby
gem 'rails', '5.0.0.rc1'

gem 'state_machines-activerecord', '0.4.0.pre'
gem 'state_machines-activemodel', '0.4.0.pre'

**Comment by seuros** [comment]
Please open issues if you see any deprecation warning.

**Comment by connorshea** [comment]
Awesome! Thank you!
