### ISSUE TITLE
Link to doc in readme or move doc into readme

### ISSUE THREAD

**Issue by lulalala** [state-machines/state_machines-activerecord#46]
The content of this page (http://www.rubydoc.info/github/state-machines/state_machines-activerecord/StateMachines/Integrations/ActiveRecord) is very important to developers, such as callback ordering.

I am wondering if we can have the readme link to this page, or better yet, move this documentation back into the readme.

**Comment by rafaelfranca** [comment]
I'm up to add a link to the official documentation in the README and also expand the README, but I don't think we should remove the class documentation too. Anyone up to open a PR?

**Comment by lulalala** [comment]
@rafaelfranca Cool I'll do that, but I am not sure what you mean by removing the class documentation? (because I only intend to add stuff to README)

**Comment by rafaelfranca** [comment]
You said move doc into readme. When I think about moving it is removing from one place and adding to other place.

**Comment by lulalala** [comment]
@rafaelfranca Ah yes, I forgot. I was thinking if I just copy and paste it to readme, future edits need to maintain both copies of the document.

So how would you like to extend the readme?
