### ISSUE TITLE
Callbacks pass when they add errors but don't return false - is this desired behaviour?

### ISSUE THREAD

**Issue by muzfuz** [state-machines/state_machines-activerecord#48]
## Between `state machine` 1.1 and 1.2, the behaviour of callbacks on ActiveRecord objects was changed.  This behaviour has been carried over into the `state_machines` gem.

Given the following class:

``` ruby
class Vehicle < ActiveRecord::Base
  state_machine :state, initial: :parked do
    event :drive do
      transition :parked => :driving
    end

    before_transition to: :driving, do: :validate_car_can_drive
  end

  def validate_car_can_drive
    errors.add(:base, "Your car is broken.") if broken?
  end

  private

  def broken?
    false
  end
end
```

These tests pass in `state_machine 1.1`, but fail in `state_machines` and  `state_machine 1.2`:

``` ruby
context "with a failing callback" do
  let(:vehicle) { Vehicle.create }

  before(:each) do
    allow(vehicle).to receive(:broken?).and_return(true)
  end

  it "does not update the state" do
    expect { vehicle.drive! rescue nil }.not_to change(vehicle, :state)
  end

  it "raises an error" do
    expect { vehicle.drive! }.to raise_error(StateMachine::InvalidTransition)
  end
end
```

No error is raised, and the state is changed.
## Changing the callback fixes these failures, and is backward compatible.

``` ruby
def validate_car_can_drive
  if broken?
    errors.add(:base, "Your car is broken.")
    false
  end
end
```

**Comment by rafaelfranca** [comment]
Yes. It is having the same bavior as Active Record callbacks. They only stop the execution if they return false, or since Rails 5.0 if you throw `:abort` symbol.

**Comment by brendon** [comment]
I noticed when I `throw(:abort)` within a `state_machines` `before_transition` callback, it complains that it is uncaught. I assume these callbacks don't operate the same as Rails 5 callbacks in AR models?
