### ISSUE TITLE
Can I use state_machines-activerecord to replace state_machine

### ISSUE THREAD

**Issue by KindleL** [state-machines/state_machines-activerecord#7]
I was using state_machine (1.2.0), can I use state_machines-activerecord to replace state_machine with nothing of my code changed?

**Comment by seuros** [comment]
@KindleL yes. Just switch gems and run your test suite. 
Report any bug please.

Thanks you

**Comment by KindleL** [comment]
@seuros OK.

Thanks for all your great job.

**Comment by titzi** [comment]
Great, but is there a reason why this gem cannot be installed using JRuby?

**Comment by seuros** [comment]
@titzi, what version of jruby are you using ?
jruby-9.0.0.0 works fine

**Comment by titzi** [comment]
the latest stable release 1.7.19

**Comment by titzi** [comment]
JRuby 9000 is still in pre

**Comment by seuros** [comment]
I see, we will have to change the ruby requirement to 1.9.3+ for the 3 gems until the 9000 is released.

**Comment by titzi** [comment]
Thank you!

**Comment by titzi** [comment]
I'm currently updating a project from Rails 4.1.9 to 4.2 and this is the last thing I need :)

**Comment by seuros** [comment]
I will do that now then.

**Comment by seuros** [comment]
done

**Comment by titzi** [comment]
Works! The bundler ran successfully. Thank you!

**Comment by francisd** [comment]
here's a difference between state_machine and this gem (v0.4.0), in rspec when migrating over.  The initial state is not a symbol, but rather a string.
```
state_machine :state, initial: :generated do
```

rspec:
```
expect(instance.state).to be == :generated
expected: == :generated
            got:    "generated"
```

this is confirmed to be a symbol in state_machine v1.2.0
