### ISSUE TITLE
Accessing scopes

### ISSUE THREAD

**Issue by stlewis** [state-machines/state_machines-activerecord#8]
I've switched my Rails 4.1 project from the unmaintained state_machine gem to this one without making any other code changes. I have a model in my application called Order.  It's initial state is 'submitted'.  Upon calling the following:

`Order.submitted`

I'm getting the following error:

`NoMethodError: undefined method `call' for #<Order::ActiveRecord_Relation:0x007ff6b39b8168>`

In general, this error appears to be related to this:
http://stackoverflow.com/questions/26413500/undefined-method-call-for-activerecordrelation

But I glanced over the code in this gem, and it _appears_ that the scopes are being defined properly?

**Comment by seuros** [comment]
Could you provide a sample app that reproduce this bug ?

**Comment by stlewis** [comment]
I don't have a running app I can share right now, sorry... -- but I've been poking around in the gem code, and saw this:

```ruby
      def create_with_scope(name)
        create_scope(name, ->(values) { ["#{attribute_column} IN (?)", values] })
      end
```

This appears to be where the magic should happen.  If we dive a little deeper to look at that create_scope method:

```ruby
        def create_scope(name, scope)
          lambda { |model, values| model.where(scope.call(values)) }
        end
```

I'm tinkering with this myself and will let you know what I come up with but...some questions:

You're passing a name and a lambda to `create_scope`...so do you need to wrap that even further in a lambda within the `create_scope` method?  Also, I can't find anywhere in any of the integrations/base classes that actually calls create_with_scope...so is this code even being invoked?

I feel like I'm missing something here :grin:

**Comment by mrclmrvn** [comment]
As with the original state-machine gem, it automatically creates scope like this:

`Order.with_state('submitted')`

And not:

`Order.submitted`

(Or maybe I missed that somewhere.)

So you have to replace with the `Order.with_state('submitted')`. Optionally, in my case, I used a different column in place of `state`, I used `status`. And access the scope via `Order.with_status('submitted')`.

HTH

**Comment by stlewis** [comment]
@mrclmrvn Right, the `with_state` stuff works, and I'm doing what you're doing -- using `status` instead of `state`.  With that said, as far as I was aware, the ability to scope by state value is something that I always thought was built in?  I'm scouring my code on the chance that I had something custom built in here at some point, but I'm not finding it...

**Comment by seuros** [comment]
@stlewis check your gemlock, if the old gem is loaded (required by a gem), it could be conflict with the current on. Also grep for StateMachine module, the new gem use StateMachines (extra s)

**Comment by stlewis** [comment]
@mrclmrvn @seuros 

I figured it out, (in a manner of speaking).  My code _was_ in fact doing some extra magic to get the `Model.state_name` style scope.  With that said, if this _isn't_ a feature, it kind of seems like it should be?   The solution in my code looks something like this:

```ruby
    statuses.each do |status|
      scope status, ->{ where(status: status.to_s) } 
    end
```

Super simple, but a nice little convenience.  I'd be happy to toss in a PR with the feature at some point since I've been staring at the code all day :grin:

**Comment by seuros** [comment]
Hmm, i'm not fan of this feature. What if i have 2 state machines in the same model with the name ?
what if a state is a reserved word (like valid).

**Comment by mrclmrvn** [comment]
Too magical for me vs `with_foo('bar')`, +1 @seuros' comment.

And should be easy to implement scope in your model.

**Comment by stlewis** [comment]
Fair points all...which actually makes me think I should consider refactoring away this application's rampant use of that style of magic.  Thanks for the help guys! As far as I'm concerned, we can close this out.

**Comment by seuros** [comment]
:+1:
