### ISSUE TITLE
Scope doesn't select records with NULL state

### ISSUE THREAD

**Issue by mksm** [state-machines/state_machines-activerecord#80]
```
class Product < ActiveRecord::Base

  state_machine do
    event :delete do
      transition any - :deleted => :deleted
    end
  end
end
```

Running `Product.without_state(:deleted)` produces:
`SELECT "products".* FROM "products" WHERE ("products"."state" NOT IN ('deleted'))`

This doesn't select records with NULL `state`. Using `IS DISTINCT FROM 'deleted'` in Postgres selects all values not equal to `deleted` including NULLs.

Using v0.5.1 and Postgres 9.6

**Comment by juanviamonte** [comment]
@mksm did you find a work around this ?

**Comment by seuros** [comment]
It not recommended to have a nil in the state. You could fix this by having a initial state. like `new`, `draft`, ect.
