### ISSUE TITLE
Support for activerecord 6.0 and rails 6.0

### ISSUE THREAD

**Issue by silvermind** [state-machines/state_machines-activerecord#83]
are there any know issues with Rails 6?

**Comment by rafaelfranca** [comment]
We already support it in the latest version.

**Comment by danielschlegel** [comment]
I cannot install gem because of active record dependency. 
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    bootstrap_form was resolved to 4.2.0, which depends on
      activemodel (>= 5.0)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      activemodel (= 6.0.0)

    state_machines-activerecord (~> 0.6.0) was resolved to 0.6.0, which depends on
      state_machines-activemodel (>= 0.5.0) was resolved to 0.5.0, which depends on
        activemodel (>= 4.1, < 5.2)
