### ISSUE TITLE
New minor release for Ruby 2.7 fix

### ISSUE THREAD

**Issue by stefano-sarioli** [state-machines/state_machines-activerecord#89]
Hi, I've seen that on master there is a commit that fixes the Ruby 2.7 warnings.

Is it possible to create a minor/bugfix release with those changes so that I can avoid depending to master inside my Gemfile?

Thanks a lot for your work on this gem 🙏

**Comment by seuros** [comment]
Yes, where is the PR ?

**Comment by stefano-sarioli** [comment]
@seuros the PR is this #88, thank you.

**Comment by stanhu** [comment]
Yes, would you mind publishing a new version? Thanks!

**Comment by magni-** [comment]
Any updates regarding publishing a gem update? 🙇

**Comment by NoahFisher** [comment]
(friendly bump) any updates on publishing this?

**Comment by spaghetticode** [comment]
having a new release would really help, thank you ❤️

**Comment by espen** [comment]
#88 makes this gem work on Ruby 3.0.0. Thanks!
