### ISSUE TITLE
Rails 4.0 support?

### ISSUE THREAD

**Issue by danielricecodes** [state-machines/state_machines-activerecord#9]
Hello,

Quick question: Do the gem authors know if this gem will work with Rails 4.0?  Is there a reason AR 4.1 is the lowest AR version?

I'm currently supporting a Rails 4.0 application, and I don't want to upgrade the application to Rails 4.1 just to try out this gem. I'd rather see if this gem could work with Rails 4.0 first.  Its also a bummer that the old state_machine gem doesn't support Rails 4.0 and this gem starts at 4.1.  Seems like a blind spot to me.

**Comment by huoxito** [comment]
@danielricecodes actually I think the original state_machine gem does support rails 4.0, or at least most of it. Spree for example is a heavy user and run just fine on the old project and rails 4.0. Are you getting any specific errors?

**Comment by seuros** [comment]
That right, the original gem support 4.0, it has some bugs that were fixed in my fork for example.

**Comment by danielricecodes** [comment]
@seuros - no not any specific issues, but since the README stated AR 4.1+ as a dependency, I thought I'd fork the activerecord and activemodel adapters, change the gemspec, and test in my application.  

I did a code review of the `state_machine` gem itself and couldn't find a Rails 4 support statement in the Readme or any code or Railties that made it obvious.  When I reviewed the code, I saw that the active record adapter had code for hooking into Rails 3 and 2, but not 4.  Maybe I missed something?  Either way, I feel I'm in a position to test the these activerecord and activemodel adapters with AR 4.0 and provide feedback (and pull requests of course) if I encounter any issues.  

Feel free to close this issue.  I'll open up a PR later if I run into any issues :smile:

**Comment by seuros** [comment]
No no, i don't want to add support for unsupported version of rails/rubies, that was actually killed the old gem.
You can use https://github.com/seuros/state_machine , it support 4.0 and was used for years in many projects without any issue.

**Comment by evolve2k** [comment]
"Feel free to close this issue. I'll open up a PR later if I run into any issues :smile:"

(Just helping out.)  Op happy that this is resolved, this issue can be closed.

**Comment by seuros** [comment]
@evolve2k  Thank you
