### ISSUE TITLE
Statemachine observer is not working as expected.

### ISSUE THREAD

**Issue by r72cccp** [state-machines/state_machines-activerecord#90]
Hi! I'm create the test case: https://github.com/r72cccp/state_machine_observer_test

To replay this problem:
* run console:
```bash
bundle exec rails c
```
* create the vehicle:
```ruby
vehicle = Vehicle.create(name: 'bmw')
```
ignite:
```ruby
v.ignite
```
=>
```
        :vehicle => #<Vehicle:0x0000563f9ac71908> {
                         :id => 2,
                       :name => "bmw",
                      :state => "idling",
            :state_update_at => nil,
                 :created_at => Fri, 11 Sep 2020 06:44:05 UTC +00:00,
                 :updated_at => Fri, 11 Sep 2020 06:44:05 UTC +00:00
        }
```
But, i'm expect to firing the methods `before_ignite`, `after_ignite`, as described [here#Observers](https://rubydoc.info/github/pluginaweek/state_machine/master/StateMachine/Integrations/ActiveRecord#Observers), but fired only `before_save` in observer [VehicleObserver](https://github.com/r72cccp/state_machine_observer_test/blob/develop/app/observers/vehicle_observer.rb).

Help me understand, please, what i'm doing wrong?

**Comment by seuros** [comment]
do you have 'state_machines-activemodel-observers' ?

**Comment by r72cccp** [comment]
> do you have 'state_machines-activemodel-observers' ?

Thank you advance. Only i added `state_machines-activemodel-observers` gem to bundle, all expected methods fired!

**Comment by subashkc** [comment]
@seuros I don't think its mentioned in the[ rubydoc guides](https://www.rubydoc.info/github/state-machines/state_machines-activerecord/StateMachines/Integrations/ActiveRecord) anywhere, I only got it going after I found this issue.

**Comment by seuros** [comment]
@subashkc , will update the docs, thanks.
